export const Products = [
	{
		id: '1',
		name: 'Nike air',
		description: 'Be best in team',
		price: 349,
		oldPrice: 390,
		discond: true,
	},
	{
		id: '2',
		name: 'Nike AirForce',
		description: 'Be best in the world',
		price: 499,
		oldPrice: 599,
		discond: true,
	},
	{
		id: '3',
		name: 'Adidas Gazzele',
		description: 'Imposible is nothing',
		price: 499,
		oldPrice: 599,
		discond: true,
	},
	{
		id: '4',
		name: 'Puma M16',
		description: 'Be best in team',
		price: 349,
		oldPrice: 390,
		discond: true,
	},
	{
		id: '5',
		name: 'Puma S90',
		description: 'Be best in team',
		price: 349,
		oldPrice: 390,
		discond: true,
	},
	{
		id: '6',
		name: 'Puma SF90',
		description: 'GG WP',
		price: 999,
		oldPrice: 1299,
		discond: true,
	},
]
